### ISSUE TITLE
 Example of using the function that displays the virtual memory

### ISSUE THREAD

**Issue by vOROn200** [CasualX/external#15]
Write an example of using the function that displays the virtual memory of the process, plz.

https://github.com/CasualX/external/blob/master/src/vm.rs#L349

**Comment by CasualX** [comment]
This function groups regions together in 'allocations' (an allocation is defined by a group of regions with the same `allocation_base`). GetMappedFileName is also queried and given (None if no associated mapped file name).

```rust
let process = ...;
process.vm_allocations(|alloc, file_name| {
    dbg!(alloc);
});
```

It's supposed to be used to find module base addresses for processes which try to hide their modules in some fashion. Either you find them by their mapped file name or region properties.

The region members are the region properties OR'd together. This gives you an idea on what kind of regions are in the allocation. Loop them again with `process.vm_regions` if needed.

**Comment by CasualX** [comment]
Let me know if you have any more questions, I'll consider this answered.
